export const UI = {
  // General
  confirm: '确定',
  cancel: '取消',
  close: '关闭',
  save: '保存',
  delete: '删除',
  copy: '复制',
  copied: '已复制',
  edit: '编辑',
  resend: '重发',
  loading: '...',

  // Title bar
  appName: '文枢',

  // Toolbar
  undo: '撤销',
  redo: '重做',
  bold: '加粗',
  italic: '斜体',
  underline: '下划线',
  wrapText: '自动换行',
  alignLeft: '左对齐',
  alignCenter: '居中对齐',
  alignRight: '右对齐',
  bgColor: '填充颜色',
  textColor: '文字颜色',
  fontSize: '字号',
  numberFormat: '数字格式',
  sortAsc: '升序排序',
  sortDesc: '降序排序',
  multiSort: '多级排序',
  autoFit: '自适应列宽',
  duplicateSheet: '复制工作表',
  exportWorkbook: '导出',
  exportCsv: 'CSV',
  importFile: '导入',
  importing: '导入中...',

  // Spreadsheet
  spreadsheet: '电子表格',
  selectAll: '全选',
  filter: '筛选',

  // Context menu
  cut: '剪切',
  copyAction: '复制',
  paste: '粘贴',
  clearContent: '清空内容',
  insertRowAbove: '在上方插入行',
  insertRowBelow: '在下方插入行',
  insertColLeft: '在左侧插入列',
  insertColRight: '在右侧插入列',
  deleteRow: '删除行',
  deleteCol: '删除列',
  autoFitRow: '自动调整行高',
  autoFitCol: '自动调整列宽',

  // Find/Replace
  find: '查找',
  findAndReplace: '查找和替换',
  findContent: '查找内容',
  replaceWith: '替换为',
  matchCase: '区分大小写',
  prevMatch: '上一个',
  nextMatch: '下一个',
  replace: '替换',
  replaceAll: '全部替换',
  noMatch: '未找到匹配项',
  matchCount: (n: number) => `找到 ${n} 个匹配项`,
  currentMatch: (idx: number) => `，当前第 ${idx} 个`,
  confirmReplaceAll: (n: number) => `确定要替换全部 ${n} 个匹配项吗？`,

  // Sort dialog
  sort: '排序',
  dataHasHeader: '数据包含标题行',
  primarySort: '主要关键字',
  secondarySort: (n: number) => `次要关键字 ${n}`,
  addSortLevel: '+ 添加排序条件',
  ascending: '升序 (A→Z)',
  descending: '降序 (Z→A)',

  // Formula bar
  ready: '就绪',
  editing: '编辑',
  entering: '输入',
  activeCell: '活动单元格',
  worksheet: '工作表',
  unnamedSheet: '未命名工作表',
  selectedArea: (rows: number, cols: number, total: number) =>
    `已选区域：${rows} 行 x ${cols} 列，共 ${total} 个单元格`,
  nonEmpty: '非空',
  numeric: '数值',
  sum: '求和',
  average: '平均值',

  // Sheet tabs
  newSheet: '新建工作表',
  renameSheet: (name: string) => `重命名"${name}"`,
  deleteSheet: '删除工作表',
  confirmDeleteSheet: (name: string) => `确定要删除"${name}"吗？`,

  // Chat
  aiAssistant: 'AI 助手',
  aiDescription: '输入指令来操作电子表格，例如填充数据、计算公式、格式化单元格或批量整理工作表。',
  settings: '设置',
  history: '历史对话',
  historyDesc: '支持切换、保留和继续之前的会话',
  newChat: '新建对话',
  chatSessionsCount: (n: number) => `${n} 个会话`,
  deleteChat: '删除对话',
  messagesCount: (n: number) => `${n} 条消息`,
  noMessages: '这条对话还没有消息',
  newConversation: '新对话',
  inputPlaceholder: '输入指令操作表格...',
  loadingPlaceholder: 'AI 正在回复，可点击右侧停止',
  stopGenerating: '停止生成',
  send: '发送',
  shiftEnterNewline: 'Shift+Enter 换行',
  replyingStatus: '正在回复中，可随时停止',
  clearHistory: '清空记录',
  copyMessage: '复制消息',
  editMessage: '编辑消息',
  deleteMessage: '删除消息',
  editHint: '`Ctrl/Cmd + Enter` 保存，`Esc` 取消',
  copyInput: '复制输入',
  copyResult: '复制结果',
  copyCode: '复制',

  // AI Config
  aiProvider: 'AI 服务提供方',
  apiKey: 'API Key',
  baseUrl: 'Base URL',
  model: '模型',
  toolMode: '工具模式',
  autoFallback: '自动回退',
  nativeTool: '原生工具调用',
  jsonTool: 'JSON 工具协议',
  injectTool: '提示词注入工具',
  noTool: '关闭工具，纯对话',
  toolModeDesc: '自动回退会优先尝试原生工具调用，失败后退到 JSON 工具协议，再退到注入工具；适用于 OpenAI-compatible、Anthropic-compatible 和 Ollama 接口。',
  testSupport: '测试支持情况',
  testing: '测试中…',
  testResult: '测试后会自动切换到当前 API 最合适的模式。',
  testFailed: (msg: string) => `测试失败：${msg}`,
  fillModelFirst: '请先填写模型名称，再测试工具支持情况。',
  fillApiKeyFirst: '请先填写 API Key，再测试工具支持情况。',

  // Import
  importValidated: '导入校验通过',
  importWithWarnings: '导入完成，但存在警告',
  importedSummary: (sheets: number, cells: number, checked: number, mismatches: number, truncated: number) =>
    `已导入 ${sheets} 个工作表、${cells} 个单元格，已校验 ${checked} 个单元格，发现 ${mismatches} 处差异，截断 ${truncated} 个超出范围的单元格。`,
  closeImportReport: '关闭导入校验结果',

  // Example prompts
  examplePrompts: [
    '在 A1:A5 填入月份',
    '创建一个销售数据表',
    '计算 B 列的总和',
    '把标题行设置为加粗',
  ],
} as const
